In [33]:
# Use this cell to begin your analyses, and add as many cells as you would like!
# importando o numpy, pandas e os dataframes
import numpy as np
import pandas as pd
df_lego_sets = pd.read_csv('datasets/lego_sets.csv')
df_parent_themes = pd.read_csv('datasets/parent_themes.csv')

In [34]:
# Printando os dataframes para ver quais são as colunas e como estão os dados
print(f'{df_lego_sets.head()} \n {df_parent_themes.head()}')

  set_num                        name  year  num_parts    theme_name  \
0    00-1             Weetabix Castle  1970      471.0        Castle
1  0011-2           Town Mini-Figures  1978        NaN  Supplemental
2  0011-3  Castle 2 for 1 Bonus Offer  1987        NaN  Lion Knights
3  0012-1          Space Mini-Figures  1979       12.0  Supplemental
4  0013-1          Space Mini-Figures  1979       12.0  Supplemental

  parent_theme
0     Legoland
1         Town
2       Castle
3        Space
4        Space
     id     name  is_licensed
0    1  Technic        False
1   22  Creator        False
2   50     Town        False
3  112   Racers        False
4  126    Space        False

In [35]:
# Vamos fazer o tratamento de dados: checar quantos NAs os dataframes possuem e corrigir de acordo com o enunciado
# df_lego_sets
print(df_lego_sets.isna().sum())
# O enunciado diz que um NA na coluna set_num significa que o valor está duplicado ou invalido, portanto devemos excluir
df_lego_sets = df_lego_sets[df_lego_sets['set_num'].notna()]

set_num          153
name             153
year               0
num_parts       5060
theme_name       153
parent_theme       0
dtype: int64

In [36]:
# Preenchendo os 
df_lego_sets = df_lego_sets.fillna(0)
print(df_lego_sets.isna().sum())

set_num         0
name            0
year            0
num_parts       0
theme_name      0
parent_theme    0
dtype: int64

In [37]:
df_lego_sets = df_lego_sets.set_index('set_num')
df_parent_themes = df_parent_themes.set_index('id')

In [38]:
list_licensed = [name for name in df_parent_themes['name'][df_parent_themes['is_licensed']==True]]
qt_licensed = df_lego_sets[df_lego_sets['parent_theme'].isin(list_licensed)]
the_force = int(len(df_lego_sets[df_lego_sets['parent_theme']=='Star Wars']) / len(qt_licensed)*100)
print(the_force)

51

In [39]:
qt_licensed

,name,year,num_parts,theme_name,parent_theme
set_num,,,,,
10018-1,Darth Maul,2001,1868.0,Star Wars,Star Wars
10019-1,Rebel Blockade Runner - UCS,2001,0.0,Star Wars Episode 4/5/6,Star Wars
10026-1,Naboo Starfighter - UCS,2002,0.0,Star Wars Episode 1,Star Wars
10030-1,Imperial Star Destroyer - UCS,2002,3115.0,Star Wars Episode 4/5/6,Star Wars
10075-1,Spider-Man Action Pack,2002,25.0,Spider-Man,Super Heroes
...,...,...,...,...,...
VP-12,Star Wars Co-Pack of 7121 and 7151,2000,2.0,Star Wars Episode 1,Star Wars
VP-2,Star Wars Co-Pack of 7110 and 7144,2001,2.0,Star Wars Episode 4/5/6,Star Wars
VP-3,Star Wars Co-Pack of 7131 and 7151,2000,2.0,Star Wars Episode 1,Star Wars
VP-4,Star Wars Co-Pack of 7101 7111 and 7171,2000,3.0,Star Wars Episode 1,Star Wars
VP-8,Star Wars Co-Pack of 7130 and 7150,2000,0.0,Star Wars Episode 4/5/6,Star Wars

In [40]:
is_sw = qt_licensed.groupby('year')['parent_theme'].agg(pd.Series.mode)
is_sw

year
1999       Star Wars
2000       Star Wars
2001       Star Wars
2002       Star Wars
2003       Star Wars
2004       Star Wars
2005       Star Wars
2006       Star Wars
2007       Star Wars
2008       Star Wars
2009       Star Wars
2010       Star Wars
2011       Star Wars
2012       Star Wars
2013       Star Wars
2014       Star Wars
2015       Star Wars
2016       Star Wars
2017    Super Heroes
Name: parent_theme, dtype: object

In [41]:
new_era = int(is_sw[is_sw != 'Star Wars'].index[0])
print(new_era)

2017

## # Introduction
<p><img src="https://assets.datacamp.com/production/project_981/img/lego_unsplash.jpg" alt="A picture of Lego characters!"></p>
<h3 id="letslookatlegosets">Let's look at Lego sets!</h3>
<p>Lego is a household name across the world, supported by a diverse toy line, hit movies, and a series of successful video games. In this project, we are going to explore a key development in the history of Lego: the introduction of licensed sets such as Star Wars, Super Heroes, and Harry Potter.</p>
<p>It may not be widely known, but Lego has had its share of ups and downs since its inception in the early 20th century. This includes a particularly rough period in the late 90s. As described in <a href="https://www.businessinsider.com/how-lego-made-a-huge-turnaround-2014-2?r=US&IR=T">this article</a>, Lego was only able to survive due to a successful internal brand (Bionicle) and the introduction of its first licensed series: Star Wars. In the instructions panel are the two questions you will need to answer to complete this project.</p>
<p>Before diving into our analysis though, let's become familiar with the two datasets that will help you with this project:<br><br></p>
<div style="background-color: #ebf4f7; color: #595959; text-align:left; vertical-align: middle; padding: 15px 25px 15px 25px; line-height: 1.6;">
    <div style="font-size:20px"><b>datasets/lego_sets.csv</b></div>
<ul>
    <li><b>set_num:</b> A code that is unique to each set in the dataset. <b><i>This column is critical, and a missing value indicates the set is a duplicate or invalid!</i></b></li>
    <li><b>set_name:</b> A name for every set in the dataset (note that this can be the same for different sets).</li>
    <li><b>year:</b> The date the set was released.</li>
    <li><b>num_parts:</b> The number of parts contained in the set.<b><i> This column is not central to our analyses, so missing values are acceptable.</i></b></li>
        <li><b>theme_name:</b> The name of the sub-theme of the set.</li>
    <li><b>parent_theme:</b> The name of the parent theme the set belongs to. Matches the `name` column of the `parent_themes` csv file.</li>
</ul>

<div style="font-size:20px"><b>datasets/parent_themes.csv</b></div>
<ul>
    <li><b>id:</b> A code that is unique to every theme.</li>
    <li><b>name:</b> The name of the parent theme.</li>
    <li><b>is_licensed:</b> A Boolean column specifying whether the theme is a licensed theme.</li>
</ul>
    </div>
<p>From here on out, it will be your task to explore and manipulate the existing data until you are able to answer the two questions described in the instructions panel. Feel free to add as many cells as necessary. Finally, remember that you are only tested on your answer, not on the methods you use to arrive at the answer!</p>
<p><em><strong>Note:</strong> If you haven't completed a DataCamp project before you should check out the <a href="https://projects.datacamp.com/projects/33">Intro to Projects</a> first to learn about the interface. In this project, you also need to know your way around <code>pandas</code> DataFrames and it's recommended that you take a look at the course <a href="https://www.datacamp.com/courses/data-manipulation-with-pandas">Data Manipulation with pandas</a>.</em></p>